# Generated by Django 5.1.1 on 2024-09-26 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postbranch',
            options={'verbose_name_plural': 'Post branches'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='branch',
        ),
        migrations.AddField(
            model_name='postcategory',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.postbranch'),
        ),
    ]
