# Generated by Django 5.1.1 on 2024-09-27 21:54

import django_summernote.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_posttag_branch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postbranch',
            options={'ordering': ('name',), 'verbose_name_plural': 'Post branches'},
        ),
        migrations.AlterModelOptions(
            name='postcategory',
            options={'ordering': ('branch__name', 'name')},
        ),
        migrations.AlterModelOptions(
            name='posttag',
            options={'ordering': ('branch__name', 'name')},
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=django_summernote.fields.SummernoteTextField(null=True),
        ),
    ]
