# Generated by Django 5.1.1 on 2024-09-22 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name_plural': '(A) Accounts'},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name_plural': '(C) Currencies'},
        ),
        migrations.AlterModelOptions(
            name='deposit',
            options={'verbose_name_plural': '(B.A) Deposit'},
        ),
        migrations.AlterModelOptions(
            name='withdraw',
            options={'verbose_name_plural': '(B.B) Withdraw'},
        ),
        migrations.CreateModel(
            name='Swap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('value_from', models.PositiveIntegerField()),
                ('value_to', models.PositiveIntegerField()),
                ('account_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_from', to='payments.account')),
                ('account_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_to', to='payments.account')),
            ],
            options={
                'verbose_name_plural': '(B.C) Swap',
            },
        ),
    ]
