# Generated by Django 5.1.1 on 2024-10-17 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderhistory'),
        ('payments', '0002_alter_currency_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositdistribution',
            name='deposit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='payments.deposit'),
        ),
        migrations.AlterField(
            model_name='depositdistribution',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_distributions', to='orders.order'),
        ),
    ]
