# Generated by Django 5.1.1 on 2024-09-22 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('obsidian_id', models.PositiveIntegerField()),
                ('minutes_working', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
