# Generated by Django 5.1.1 on 2024-09-28 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('obsidian_id', models.PositiveIntegerField()),
                ('minutes_working', models.PositiveIntegerField()),
                ('document', models.FileField(blank=True, null=True, upload_to='sessions/session/document/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SessionDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('minutes', models.PositiveIntegerField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='sessions_.session')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_distributions', to='orders.task')),
            ],
            options={
                'verbose_name_plural': 'Session distribution',
            },
        ),
    ]
