# Generated by Django 5.1.1 on 2024-09-22 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='sessions/session/document/'),
        ),
    ]
