# Generated by Django 5.1.1 on 2024-10-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='obsidian_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
