# Generated by Django 5.1.1 on 2024-10-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_', '0002_alter_session_obsidian_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiondistribution',
            name='minutes',
            field=models.PositiveIntegerField(help_text="Sum of minutes in session have to be equal to it's minutes"),
        ),
    ]
