# Generated by Django 5.1.1 on 2024-09-28 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_epic_options_alter_order_options_and_more'),
        ('sessions_', '0002_session_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('minutes', models.PositiveIntegerField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.task')),
            ],
            options={
                'verbose_name_plural': 'Session distribution',
            },
        ),
    ]
