# Generated by Django 5.1.1 on 2024-09-28 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_', '0003_sessiondistribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiondistribution',
            name='session',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sessions_.session'),
            preserve_default=False,
        ),
    ]
