# Generated by Django 5.1.1 on 2024-12-09 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_', '0003_alter_sessiondistribution_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('start', 'Start'), ('finish', 'Finish'), ('regular', 'Regular'), ('break_start', 'Break start'), ('break_end', 'Break end')], max_length=12)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='sessions_.session')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
