# Generated by Django 5.1.1 on 2024-09-28 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_epic_options_alter_order_options_and_more'),
        ('sessions_', '0004_sessiondistribution_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiondistribution',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='orders.task'),
        ),
    ]
