# Generated by Django 5.1.1 on 2024-12-09 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_', '0004_sessionsignal'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='datetime_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='datetime_start',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 12, 9, 18, 4, 9, 939434, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
