# Generated by Django 5.1.1 on 2024-09-28 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_status'),
        ('sessions_', '0005_alter_sessiondistribution_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiondistribution',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='sessions_.session'),
        ),
        migrations.AlterField(
            model_name='sessiondistribution',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_distributions', to='orders.task'),
        ),
    ]
