# Generated by Django 5.1.1 on 2024-10-27 17:19

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0004_deposit_date_withdraw_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositSummary',
            fields=[
            ],
            options={
                'verbose_name_plural': ' Deposit summary',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('payments.deposit',),
        ),
    ]
