# Generated by Django 5.1.1 on 2024-12-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='channel',
            field=models.CharField(blank=True, choices=[('kwork', 'Kwork'), ('upwork', 'Upwork'), ('facebook', 'Facebook'), ('threads', 'Threads')], max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='full_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='respectfull_communication',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='telegram_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
