# Generated by Django 5.1.1 on 2024-10-17 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderhistory'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
    ]
