# Generated by Django 5.1.1 on 2024-10-17 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('services', '0002_portfolio_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='order',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
