# Generated by Django 5.1.1 on 2024-09-25 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_programminglanguage_alter_service_options_technology'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technology',
            options={'ordering': ('programming_language__name', 'name'), 'verbose_name_plural': 'Technologies'},
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
