# Generated by Django 5.1.1 on 2024-11-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_portfolio_order_portfolio_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='is_fake',
            field=models.BooleanField(default=False),
        ),
    ]
