# Generated by Django 5.1.1 on 2025-01-02 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_portfolio_is_fake'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='turnkey',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='services.service'),
        ),
    ]
