# Generated by Django 5.1.1 on 2025-01-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_portfolio_turnkey_alter_portfolio_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='turnkey',
        ),
        migrations.AddField(
            model_name='service',
            name='is_turnkey',
            field=models.BooleanField(default=False),
        ),
    ]
