# Generated by Django 5.1.1 on 2025-01-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_remove_portfolio_turnkey_service_is_turnkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
