# Generated by Django 5.1.1 on 2024-09-26 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_technologyarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.technologyarea'),
        ),
    ]
