# Generated by Django 5.1.1 on 2024-09-26 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_technology_area'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programminglanguage',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='technologyarea',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='service',
            name='technologies',
        ),
        migrations.AddField(
            model_name='service',
            name='technology_areas',
            field=models.ManyToManyField(blank=True, to='services.technologyarea'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='services.technologyarea'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='programming_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='services.programminglanguage'),
        ),
    ]
