# Generated by Django 5.1.1 on 2025-01-08 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_portfolio_github_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='HTMLTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('url_github', models.URLField()),
                ('url_themeforest', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'HTML themes',
            },
        ),
        migrations.AddField(
            model_name='portfolio',
            name='html_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.htmltheme'),
        ),
    ]
