# Generated by Django 5.1.1 on 2025-01-08 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_htmltheme_url_github_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='htmltheme',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
