# Generated by Django 5.1.1 on 2025-01-08 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_htmltheme_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='html_theme',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.htmltheme'),
        ),
    ]
