# Generated by Django 5.1.1 on 2025-01-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_alter_portfolio_html_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='htmltheme',
            name='is_css_minified',
            field=models.BooleanField(default=True),
        ),
    ]
