# Generated by Django 5.1.1 on 2025-02-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_htmltheme_is_css_minified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
