# Generated by Django 5.1.1 on 2025-01-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=64)),
                ('company_logo', models.ImageField(upload_to='website/working-experience/company-logo/')),
                ('position_name', models.CharField(max_length=64)),
                ('year_start', models.PositiveIntegerField()),
                ('year_end', models.PositiveIntegerField()),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ('year_start',),
            },
        ),
    ]
