# Generated by Django 5.1.1 on 2025-01-13 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_customerlogo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerLogo',
        ),
    ]
