# Generated by Django 5.1.1 on 2025-02-04 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_delete_customerlogo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkingExperience',
        ),
    ]
