# Generated by Django 5.1.1 on 2025-02-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0004_delete_workingexperience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.PositiveIntegerField()),
                ('projects', models.PositiveIntegerField()),
                ('clients', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
