# Generated by Django 5.1.1 on 2025-02-04 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stats',
            old_name='clients',
            new_name='customers',
        ),
    ]
