# Generated by Django 5.1.1 on 2024-11-10 15:38

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions_', '0003_alter_sessiondistribution_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionSummaryByDays',
            fields=[
            ],
            options={
                'verbose_name_plural': ' Session summary (by days)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sessions_.session',),
        ),
        migrations.CreateModel(
            name='SessionSummaryByMonths',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Session summary (by months)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sessions_.session',),
        ),
    ]
