# Generated by Django 5.1.1 on 2025-01-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplace',
            name='link',
            field=models.URLField(default='https://google.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marketplace',
            name='reviews_count',
            field=models.PositiveIntegerField(default=5),
            preserve_default=False,
        ),
    ]
