# Generated by Django 5.1.1 on 2024-09-25 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('marketplaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketplace',
            options={'ordering': ('-is_active', 'name')},
        ),
        migrations.AlterModelOptions(
            name='proposal',
            options={'ordering': ('status', 'date_sent')},
        ),
        migrations.AlterField(
            model_name='marketplace',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='marketplaceaccount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='marketplace_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketplaces.marketplaceaccount'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('negotiation', 'Negotiation'), ('succeeded', 'Succeeded'), ('expired', 'Expired')], default='pending', max_length=32),
        ),
    ]
