# Generated by Django 5.1.1 on 2025-02-04 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaces', '0002_marketplace_link_marketplace_reviews_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketplace',
            options={'ordering': ('-is_active', '-reviews_count', 'name')},
        ),
    ]
