# Generated by Django 5.1.1 on 2024-09-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaces', '0002_alter_marketplace_options_alter_proposal_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='customer_title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
