# Generated by Django 5.1.1 on 2025-02-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaces', '0003_alter_marketplace_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketplace',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='marketplaceaccount',
            options={'ordering': ('is_active', 'reviews_count')},
        ),
        migrations.RemoveField(
            model_name='marketplace',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='marketplace',
            name='reviews_count',
        ),
        migrations.AddField(
            model_name='marketplaceaccount',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketplaceaccount',
            name='reviews_count',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
    ]
