# Generated by Django 5.1.1 on 2024-09-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaces', '0004_alter_proposal_options_alter_proposal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='customer_feedback',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
