# Generated by Django 5.1.1 on 2024-09-28 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('1', 'active'), ('2', 'pending'), ('3', 'finished'), ('4', 'canceled')], default='2', max_length=4)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'verbose_name_plural': '(A) Orders',
            },
        ),
        migrations.CreateModel(
            name='Epic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=64)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epics', to='orders.order')),
            ],
            options={
                'verbose_name_plural': '(B) Epics',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('pending', 'Pending'), ('in_progress', 'In progress'), ('done', 'Done')], max_length=24)),
                ('is_backlog', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('estimate', models.FloatField(default=0)),
                ('epic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='orders.epic')),
            ],
            options={
                'verbose_name_plural': '(C) Tasks',
            },
        ),
    ]
