# Generated by Django 5.1.1 on 2024-09-09 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_epic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('pending', 'Pending'), ('in_progress', 'In progress'), ('done', 'Done')], max_length=24)),
                ('is_backlog', models.BooleanField(default=True)),
                ('epic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.epic')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
