# Generated by Django 5.1.1 on 2024-09-28 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_epic_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'active'), ('2', 'pending'), ('3', 'finished'), ('4', 'canceled')], default='2', max_length=4),
        ),
    ]
